### PR TITLE
fix: logger colors

### LINKED ISSUE #171: Replace Logger package with AtSignLogger and stdout
A chore task to make logging in this tool consistent with other projects:

- Remove logger package
- Move all error and warning logging to AtSignLogger
  - Add a verbose flag to command_runner's topLevelResults to set AtSignLogger.root_level
- Move all info logging to direct stdout

### PR DESCRIPTION
**Pull request by xavierchanth**
closes #171 

**- What I did**

Fixed accessibility issues with at_apps stdout logger in light mode:
-  Replace `logger`'s AnsiColor class with `chalk`'s functions

**- How I did it**

Local changes.

**- How to verify it**
Before:
CleanShot 2022-10-05 at 18 45 31

After:
CleanShot 2022-10-05 at 18 44 22

**- Description for the changelog**
fix: logger colors

### CODE REVIEW

**Review by JeremyTubongbanua — APPROVED** [review]
Cool

I also wrote this in case you need

```dart
enum Colors {
    
  black('\u001b[30m'), red('\u001b[31m'), green('\u001b[32m'), yellow('\u001b[33m'),
  blue('\u001b[34m'), magenta('\u001b[35m'), cyan('\u001b[36m'), white('\u001b[37m'), reset('\u001b[0m'),;

  final String _code;
  const Colors(this._code);

  String get code => _code;

}
```

File: packages/at_app/lib/src/version.dart [hunk 1]
```diff
@@ -1,2 +1,2 @@
 // Generated code. Do not modify.
```
Comment (cpswan) [inline packages/at_app/lib/src/version.dart:1]: Should this be checked in?

**Review by cpswan — APPROVED** [review]

File: packages/at_app/lib/src/version.dart (hunk 1 above)
Comment (xavierchanth) [reply packages/at_app/lib/src/version.dart:1]: Yep, still required for `at_app --version` but the build pipeline automatically updates this file based on the value in pubspec.yaml
